// The Pacenote plugin contract, version 1.
//
// A plugin is a separate process. The host starts it, hands it a handshake on
// standard output, and speaks gRPC to it over a local socket. Everything below
// is that conversation and nothing else.
//
// The bodies are JSON documents rather than protobuf messages. That is
// deliberate: this product already speaks JSON on the wire between the client
// and the server, the facts a coach is given are the same facts in both places,
// and one schema documented once is worth more than two that can drift. The
// Go spellings are in the root of this module; any other language reads the
// same JSON.
//
// Credentials are the exception. They travel in their own map field and never
// inside a JSON body, so a plugin author who logs the request they were given
// cannot leak the operator's key by accident.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SettingsRequest is empty. What a plugin needs configured cannot depend on the
// configuration, or a fresh installation would have no way in.
type SettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsRequest) Reset() {
	*x = SettingsRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsRequest) ProtoMessage() {}

func (x *SettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsRequest.ProtoReflect.Descriptor instead.
func (*SettingsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// SettingsResponse carries a JSON array of Setting.
type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingsJson  []byte                 `protobuf:"bytes,1,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *SettingsResponse) GetSettingsJson() []byte {
	if x != nil {
		return x.SettingsJson
	}
	return nil
}

// NotifyRequest carries a JSON Event, the operator's settings for this plugin,
// and the credentials this plugin declared.
type NotifyRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventJson  []byte                 `protobuf:"bytes,1,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`
	ValuesJson []byte                 `protobuf:"bytes,2,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	// secrets maps a declared setting name to the credential the core holds for
	// it. Present only for the settings this plugin itself declared as secret:
	// no plugin ever receives another plugin's.
	Secrets       map[string]string `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyRequest) GetEventJson() []byte {
	if x != nil {
		return x.EventJson
	}
	return nil
}

func (x *NotifyRequest) GetValuesJson() []byte {
	if x != nil {
		return x.ValuesJson
	}
	return nil
}

func (x *NotifyRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// NotifyResponse carries a JSON Usage: what the event cost, if anything.
type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsageJson     []byte                 `protobuf:"bytes,1,opt,name=usage_json,json=usageJson,proto3" json:"usage_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyResponse) GetUsageJson() []byte {
	if x != nil {
		return x.UsageJson
	}
	return nil
}

// AnswerRequest carries a JSON Request, the settings and the secrets, on the
// same terms as NotifyRequest.
type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	ValuesJson    []byte                 `protobuf:"bytes,2,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	Secrets       map[string]string      `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

func (x *AnswerRequest) GetValuesJson() []byte {
	if x != nil {
		return x.ValuesJson
	}
	return nil
}

func (x *AnswerRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// AnswerResponse carries a JSON Response, which includes the Usage the call
// cost. A plugin that answers without reporting what it spent is reporting
// zero, and the operator's cap will believe it.
type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  []byte                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

// ServeRequest is one HTTP request, forwarded whole.
type ServeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// method is the HTTP method, uppercased.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// path is what follows /plugin/<name>, always beginning with a slash. The
	// plugin's own routing starts here.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// query is the raw query string, without the leading question mark.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// headers are the request's headers, canonicalised, minus the ones that
	// belong to the host: no cookie of the host's own reaches a plugin, because
	// a plugin holding the operator's admin session would be the operator.
	Headers map[string]*HeaderValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// body is the request body, already capped by the host.
	Body []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// caller is what the host knows about whoever made the request.
	Caller *Caller `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	// prefix is the address this plugin is mounted at, so that it can build
	// links and form actions that come back to itself.
	Prefix string `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// base_url is the operator's own public address, for the links a plugin
	// sends somewhere else and expects back.
	BaseUrl string `protobuf:"bytes,8,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// values_json and secrets are the plugin's configuration, on the same terms
	// as every other call.
	ValuesJson    []byte            `protobuf:"bytes,9,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	Secrets       map[string]string `protobuf:"bytes,10,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeRequest) Reset() {
	*x = ServeRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeRequest) ProtoMessage() {}

func (x *ServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeRequest.ProtoReflect.Descriptor instead.
func (*ServeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ServeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ServeRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ServeRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServeRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *ServeRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ServeRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ServeRequest) GetValuesJson() []byte {
	if x != nil {
		return x.ValuesJson
	}
	return nil
}

func (x *ServeRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// HeaderValues is one header's values, because protobuf maps cannot hold a
// repeated field directly.
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Caller is who the host believes made the request. Every field is the host's
// word, not the caller's: none of it is read from a header a client can set.
type Caller struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// driver_slug is the signed-in driver, or empty for nobody. It is set only
	// where the host holds a driver session, which is the host's to mint.
	DriverSlug string `protobuf:"bytes,1,opt,name=driver_slug,json=driverSlug,proto3" json:"driver_slug,omitempty"`
	// driver_name is that driver's name, so a plugin need not look it up to say
	// hello.
	DriverName string `protobuf:"bytes,2,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	// admin_email is the signed-in operator, or empty. A plugin serving an
	// operator-only page is told who is reading it.
	AdminEmail string `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	// remote is the address the request came from, as the host resolved it
	// behind whatever proxy the operator runs.
	Remote        string `protobuf:"bytes,4,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caller) Reset() {
	*x = Caller{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caller) ProtoMessage() {}

func (x *Caller) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caller.ProtoReflect.Descriptor instead.
func (*Caller) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Caller) GetDriverSlug() string {
	if x != nil {
		return x.DriverSlug
	}
	return ""
}

func (x *Caller) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *Caller) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *Caller) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

// ServeResponse is what to answer with.
type ServeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the HTTP status code. Zero means 200.
	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// headers are the headers to write. The host refuses the ones that are its
	// own to decide, and allows a plugin to set only its own cookies.
	Headers map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// body is the response body, capped by the host.
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// sign_in asks the host to establish a driver session for this browser, by
	// the driver's slug. It is how a plugin that authenticates drivers hands the
	// result back: the plugin says who, and the host mints the session. A plugin
	// never sees a session token and cannot make one.
	SignIn string `protobuf:"bytes,4,opt,name=sign_in,json=signIn,proto3" json:"sign_in,omitempty"`
	// sign_out ends whatever driver session this browser has.
	SignOut bool `protobuf:"varint,5,opt,name=sign_out,json=signOut,proto3" json:"sign_out,omitempty"`
	// usage_json is what serving the request cost, if anything, on the same
	// terms as every other call.
	UsageJson     []byte `protobuf:"bytes,6,opt,name=usage_json,json=usageJson,proto3" json:"usage_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeResponse) Reset() {
	*x = ServeResponse{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeResponse) ProtoMessage() {}

func (x *ServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeResponse.ProtoReflect.Descriptor instead.
func (*ServeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ServeResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServeResponse) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ServeResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServeResponse) GetSignIn() string {
	if x != nil {
		return x.SignIn
	}
	return ""
}

func (x *ServeResponse) GetSignOut() bool {
	if x != nil {
		return x.SignOut
	}
	return false
}

func (x *ServeResponse) GetUsageJson() []byte {
	if x != nil {
		return x.UsageJson
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x12pacenote.plugin.v1\"\x11\n" +
	"\x0fSettingsRequest\"7\n" +
	"\x10SettingsResponse\x12#\n" +
	"\rsettings_json\x18\x01 \x01(\fR\fsettingsJson\"\xd5\x01\n" +
	"\rNotifyRequest\x12\x1d\n" +
	"\n" +
	"event_json\x18\x01 \x01(\fR\teventJson\x12\x1f\n" +
	"\vvalues_json\x18\x02 \x01(\fR\n" +
	"valuesJson\x12H\n" +
	"\asecrets\x18\x03 \x03(\v2..pacenote.plugin.v1.NotifyRequest.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0eNotifyResponse\x12\x1d\n" +
	"\n" +
	"usage_json\x18\x01 \x01(\fR\tusageJson\"\xd9\x01\n" +
	"\rAnswerRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\x12\x1f\n" +
	"\vvalues_json\x18\x02 \x01(\fR\n" +
	"valuesJson\x12H\n" +
	"\asecrets\x18\x03 \x03(\v2..pacenote.plugin.v1.AnswerRequest.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x0eAnswerResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\fR\fresponseJson\"\x98\x04\n" +
	"\fServeRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12G\n" +
	"\aheaders\x18\x04 \x03(\v2-.pacenote.plugin.v1.ServeRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x122\n" +
	"\x06caller\x18\x06 \x01(\v2\x1a.pacenote.plugin.v1.CallerR\x06caller\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12\x19\n" +
	"\bbase_url\x18\b \x01(\tR\abaseUrl\x12\x1f\n" +
	"\vvalues_json\x18\t \x01(\fR\n" +
	"valuesJson\x12G\n" +
	"\asecrets\x18\n" +
	" \x03(\v2-.pacenote.plugin.v1.ServeRequest.SecretsEntryR\asecrets\x1a\\\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .pacenote.plugin.v1.HeaderValuesR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x83\x01\n" +
	"\x06Caller\x12\x1f\n" +
	"\vdriver_slug\x18\x01 \x01(\tR\n" +
	"driverSlug\x12\x1f\n" +
	"\vdriver_name\x18\x02 \x01(\tR\n" +
	"driverName\x12\x1f\n" +
	"\vadmin_email\x18\x03 \x01(\tR\n" +
	"adminEmail\x12\x16\n" +
	"\x06remote\x18\x04 \x01(\tR\x06remote\"\xb6\x02\n" +
	"\rServeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12H\n" +
	"\aheaders\x18\x02 \x03(\v2..pacenote.plugin.v1.ServeResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x17\n" +
	"\asign_in\x18\x04 \x01(\tR\x06signIn\x12\x19\n" +
	"\bsign_out\x18\x05 \x01(\bR\asignOut\x12\x1d\n" +
	"\n" +
	"usage_json\x18\x06 \x01(\fR\tusageJson\x1a\\\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .pacenote.plugin.v1.HeaderValuesR\x05value:\x028\x012\xcf\x02\n" +
	"\x06Plugin\x12U\n" +
	"\bSettings\x12#.pacenote.plugin.v1.SettingsRequest\x1a$.pacenote.plugin.v1.SettingsResponse\x12O\n" +
	"\x06Notify\x12!.pacenote.plugin.v1.NotifyRequest\x1a\".pacenote.plugin.v1.NotifyResponse\x12O\n" +
	"\x06Answer\x12!.pacenote.plugin.v1.AnswerRequest\x1a\".pacenote.plugin.v1.AnswerResponse\x12L\n" +
	"\x05Serve\x12 .pacenote.plugin.v1.ServeRequest\x1a!.pacenote.plugin.v1.ServeResponseB,Z*github.com/pacenote-sim/plugin/internal/pbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_plugin_proto_goTypes = []any{
	(*SettingsRequest)(nil),  // 0: pacenote.plugin.v1.SettingsRequest
	(*SettingsResponse)(nil), // 1: pacenote.plugin.v1.SettingsResponse
	(*NotifyRequest)(nil),    // 2: pacenote.plugin.v1.NotifyRequest
	(*NotifyResponse)(nil),   // 3: pacenote.plugin.v1.NotifyResponse
	(*AnswerRequest)(nil),    // 4: pacenote.plugin.v1.AnswerRequest
	(*AnswerResponse)(nil),   // 5: pacenote.plugin.v1.AnswerResponse
	(*ServeRequest)(nil),     // 6: pacenote.plugin.v1.ServeRequest
	(*HeaderValues)(nil),     // 7: pacenote.plugin.v1.HeaderValues
	(*Caller)(nil),           // 8: pacenote.plugin.v1.Caller
	(*ServeResponse)(nil),    // 9: pacenote.plugin.v1.ServeResponse
	nil,                      // 10: pacenote.plugin.v1.NotifyRequest.SecretsEntry
	nil,                      // 11: pacenote.plugin.v1.AnswerRequest.SecretsEntry
	nil,                      // 12: pacenote.plugin.v1.ServeRequest.HeadersEntry
	nil,                      // 13: pacenote.plugin.v1.ServeRequest.SecretsEntry
	nil,                      // 14: pacenote.plugin.v1.ServeResponse.HeadersEntry
}
var file_plugin_proto_depIdxs = []int32{
	10, // 0: pacenote.plugin.v1.NotifyRequest.secrets:type_name -> pacenote.plugin.v1.NotifyRequest.SecretsEntry
	11, // 1: pacenote.plugin.v1.AnswerRequest.secrets:type_name -> pacenote.plugin.v1.AnswerRequest.SecretsEntry
	12, // 2: pacenote.plugin.v1.ServeRequest.headers:type_name -> pacenote.plugin.v1.ServeRequest.HeadersEntry
	8,  // 3: pacenote.plugin.v1.ServeRequest.caller:type_name -> pacenote.plugin.v1.Caller
	13, // 4: pacenote.plugin.v1.ServeRequest.secrets:type_name -> pacenote.plugin.v1.ServeRequest.SecretsEntry
	14, // 5: pacenote.plugin.v1.ServeResponse.headers:type_name -> pacenote.plugin.v1.ServeResponse.HeadersEntry
	7,  // 6: pacenote.plugin.v1.ServeRequest.HeadersEntry.value:type_name -> pacenote.plugin.v1.HeaderValues
	7,  // 7: pacenote.plugin.v1.ServeResponse.HeadersEntry.value:type_name -> pacenote.plugin.v1.HeaderValues
	0,  // 8: pacenote.plugin.v1.Plugin.Settings:input_type -> pacenote.plugin.v1.SettingsRequest
	2,  // 9: pacenote.plugin.v1.Plugin.Notify:input_type -> pacenote.plugin.v1.NotifyRequest
	4,  // 10: pacenote.plugin.v1.Plugin.Answer:input_type -> pacenote.plugin.v1.AnswerRequest
	6,  // 11: pacenote.plugin.v1.Plugin.Serve:input_type -> pacenote.plugin.v1.ServeRequest
	1,  // 12: pacenote.plugin.v1.Plugin.Settings:output_type -> pacenote.plugin.v1.SettingsResponse
	3,  // 13: pacenote.plugin.v1.Plugin.Notify:output_type -> pacenote.plugin.v1.NotifyResponse
	5,  // 14: pacenote.plugin.v1.Plugin.Answer:output_type -> pacenote.plugin.v1.AnswerResponse
	9,  // 15: pacenote.plugin.v1.Plugin.Serve:output_type -> pacenote.plugin.v1.ServeResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
