// The Pacenote plugin contract, version 1.
//
// A plugin is a separate process. The host starts it, hands it a handshake on
// standard output, and speaks gRPC to it over a local socket. Everything below
// is that conversation and nothing else.
//
// The bodies are JSON documents rather than protobuf messages. That is
// deliberate: this product already speaks JSON on the wire between the client
// and the server, the facts a coach is given are the same facts in both places,
// and one schema documented once is worth more than two that can drift. The
// Go spellings are in the root of this module; any other language reads the
// same JSON.
//
// Credentials are the exception. They travel in their own map field and never
// inside a JSON body, so a plugin author who logs the request they were given
// cannot leak the operator's key by accident.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Settings_FullMethodName = "/pacenote.plugin.v1.Plugin/Settings"
	Plugin_Notify_FullMethodName   = "/pacenote.plugin.v1.Plugin/Notify"
	Plugin_Answer_FullMethodName   = "/pacenote.plugin.v1.Plugin/Answer"
	Plugin_Serve_FullMethodName    = "/pacenote.plugin.v1.Plugin/Serve"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plugin is what every plugin serves. Four calls, matching the four things a
// host does: ask what to configure, say what happened, ask for something, and
// hand over a request somebody made of it.
type PluginClient interface {
	// Settings declares what the operator has to fill in. The host asks once,
	// when the plugin starts, and stores the answer so the panel can render the
	// form whether or not the plugin is running.
	Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	// Notify tells the plugin something happened. The host does not wait for the
	// answer before carrying on with its own work, but the answer still carries
	// what the call spent, because a plugin that burns the operator's tokens on
	// an event must be metered like any other call.
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// Answer asks the plugin for something and waits. The deadline is on the
	// context; a plugin that misses it is skipped and the caller is told so.
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
	// Serve hands over one HTTP request made to /plugin/<name>/..., and takes
	// back what to answer with. It is how a plugin puts a page or an endpoint on
	// the operator's server without being linked into it.
	//
	// One request, one response, both whole: there is no streaming and no
	// upgrade, so a plugin cannot hold a connection open against the host. The
	// host caps both bodies and the time this may take, and a plugin that misses
	// the deadline is answered for.
	Serve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, Plugin_Settings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, Plugin_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, Plugin_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Serve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServeResponse)
	err := c.cc.Invoke(ctx, Plugin_Serve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Plugin is what every plugin serves. Four calls, matching the four things a
// host does: ask what to configure, say what happened, ask for something, and
// hand over a request somebody made of it.
type PluginServer interface {
	// Settings declares what the operator has to fill in. The host asks once,
	// when the plugin starts, and stores the answer so the panel can render the
	// form whether or not the plugin is running.
	Settings(context.Context, *SettingsRequest) (*SettingsResponse, error)
	// Notify tells the plugin something happened. The host does not wait for the
	// answer before carrying on with its own work, but the answer still carries
	// what the call spent, because a plugin that burns the operator's tokens on
	// an event must be metered like any other call.
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// Answer asks the plugin for something and waits. The deadline is on the
	// context; a plugin that misses it is skipped and the caller is told so.
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	// Serve hands over one HTTP request made to /plugin/<name>/..., and takes
	// back what to answer with. It is how a plugin puts a page or an endpoint on
	// the operator's server without being linked into it.
	//
	// One request, one response, both whole: there is no streaming and no
	// upgrade, so a plugin cannot hold a connection open against the host. The
	// host caps both bodies and the time this may take, and a plugin that misses
	// the deadline is answered for.
	Serve(context.Context, *ServeRequest) (*ServeResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Settings(context.Context, *SettingsRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Settings not implemented")
}
func (UnimplementedPluginServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedPluginServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedPluginServer) Serve(context.Context, *ServeRequest) (*ServeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Serve not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Settings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Settings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Settings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Settings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Serve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Serve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Serve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Serve(ctx, req.(*ServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pacenote.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Settings",
			Handler:    _Plugin_Settings_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Plugin_Notify_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _Plugin_Answer_Handler,
		},
		{
			MethodName: "Serve",
			Handler:    _Plugin_Serve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
